# fly.toml app configuration file generated for itpa2-purple-snowflake-1149-icy-waterfall-1046 on 2024-01-16T21:34:00-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "itpa2-purple-snowflake-1149-icy-waterfall-1046"
primary_region = "dfw"
console_command = "/code/manage.py shell"

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
